# Generated by Django 2.2.10 on 2020-06-11 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0040_remove_usuario_nombreusuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreLaboratorio', models.CharField(max_length=100)),
                ('jefeLaboratorio', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['nombreLaboratorio'],
            },
        ),
        migrations.CreateModel(
            name='ProgramaPosgrado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePrograma', models.CharField(max_length=50)),
                ('siglasPrograma', models.CharField(max_length=10)),
                ('coordinadorPrograma', models.CharField(max_length=200)),
                ('semanasSemestrePrograma', models.IntegerField()),
            ],
            options={
                'ordering': ['nombrePrograma'],
            },
        ),
        migrations.CreateModel(
            name='UnidadAprendizaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUA', models.CharField(max_length=100)),
                ('tipoUA', models.CharField(choices=[('OBLIGATORIA', 'Obligatoria'), ('OPTATIVA', 'Optativa')], max_length=15)),
                ('tipoHorasUA', models.CharField(choices=[('TEORIA', 'Teoria'), ('PRACTICA', 'Practica'), ('TEORICOPRACTICA', 'Teorico-Practica'), ('SEMINARIO', 'Seminario'), ('ESTANCIA', 'Estancia')], max_length=15)),
                ('horasSemanaUA', models.IntegerField()),
                ('horasSemestreUA', models.IntegerField()),
                ('creditosUA', models.DecimalField(decimal_places=2, max_digits=4)),
                ('creditosSatcaUA', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'ordering': ['nombreUA'],
            },
        ),
        migrations.CreateModel(
            name='SituacionEscolar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=6)),
                ('semestre', models.IntegerField()),
                ('primerParcial', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('segundoParcial', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('tercerParcial', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('extraordinario', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('calificacionFinal', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('evaluacionProfesor', models.BooleanField()),
                ('UA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ofertaEducativa.UnidadAprendizaje')),
                ('profesorUDA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Profesor')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
