# Generated by Django 2.2.10 on 2020-06-11 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ofertaEducativa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='situacionescolar',
            name='profesorUDA',
        ),
    ]
