# Generated by Django 2.2.10 on 2020-06-11 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ofertaEducativa', '0002_remove_situacionescolar_profesoruda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='situacionescolar',
            name='UA',
        ),
    ]
