# Generated by Django 2.2.10 on 2020-06-11 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertaEducativa', '0003_remove_situacionescolar_ua'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='situacionescolar',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='situacionescolar',
            name='calificacionFinal',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='situacionescolar',
            name='extraordinario',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='situacionescolar',
            name='primerParcial',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='situacionescolar',
            name='segundoParcial',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='situacionescolar',
            name='tercerParcial',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
