# Generated by Django 2.2.10 on 2020-06-11 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0040_remove_usuario_nombreusuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ofertaEducativa', '0004_auto_20200610_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='situacionescolar',
            name='UA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ofertaEducativa.UnidadAprendizaje'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='situacionescolar',
            name='profesorUDA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Profesor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='situacionescolar',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='situacionescolar',
            name='calificacionFinal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='situacionescolar',
            name='extraordinario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='situacionescolar',
            name='primerParcial',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='situacionescolar',
            name='segundoParcial',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='situacionescolar',
            name='tercerParcial',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4),
        ),
    ]
