# Generated by Django 2.2.10 on 2020-06-11 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ofertaEducativa', '0005_auto_20200610_2123'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SituacionEscolar',
        ),
    ]
