# Generated by Django 2.2.10 on 2020-06-11 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0040_remove_usuario_nombreusuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ofertaEducativa', '0006_delete_situacionescolar'),
    ]

    operations = [
        migrations.CreateModel(
            name='SituacionEscolar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=6)),
                ('semestre', models.IntegerField()),
                ('primerParcial', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('segundoParcial', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('tercerParcial', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('extraordinario', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('calificacionFinal', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('evaluacionProfesor', models.BooleanField()),
                ('UA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ofertaEducativa.UnidadAprendizaje')),
                ('profesorUDA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Profesor')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
