# Generated by Django 2.2.10 on 2020-06-11 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ofertaEducativa', '0007_situacionescolar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SituacionEscolar',
        ),
    ]
