# Generated by Django 2.2.10 on 2020-02-12 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoAnimal', models.CharField(max_length=20)),
                ('garras', models.BooleanField()),
                ('alas', models.BooleanField()),
                ('plumas', models.BooleanField()),
                ('cola', models.BooleanField()),
            ],
        ),
    ]
