# Generated by Django 2.2.10 on 2020-02-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bosque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frutos', models.BooleanField()),
                ('nombreFruto', models.CharField(max_length=20)),
            ],
        ),
    ]
