# Generated by Django 2.2.10 on 2020-02-12 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bosque', '0002_planta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planta',
            name='nombreFruto',
        ),
    ]
