# Generated by Django 2.2.10 on 2020-02-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bosque', '0003_remove_planta_nombrefruto'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='nombreFruto',
            field=models.CharField(default='Manzana', max_length=20),
        ),
    ]
