# Generated by Django 2.2.10 on 2020-02-12 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bosque', '0004_planta_nombrefruto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Planta',
        ),
    ]
