# Generated by Django 2.2.10 on 2020-02-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bosque', '0006_planta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='tipoAnimal',
            new_name='nombreAnimal',
        ),
        migrations.AlterField(
            model_name='planta',
            name='nombreFruto',
            field=models.CharField(default='manzana', max_length=20),
        ),
    ]
