# Generated by Django 2.2.10 on 2020-02-19 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bosque', '0007_auto_20200213_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='nombrePlanta',
            field=models.CharField(default='manzana', max_length=20),
        ),
    ]
