# Generated by Django 2.2.10 on 2020-02-19 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bosque', '0008_planta_nombreplanta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='nombreFruto',
            field=models.CharField(blank=True, default='manzana', max_length=20),
        ),
    ]
