# Generated by Django 2.2.10 on 2020-02-19 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bosque', '0009_auto_20200218_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='nombreFruto',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='planta',
            name='nombrePlanta',
            field=models.CharField(default='Manzana', max_length=20),
        ),
    ]
