# Generated by Django 2.2.11 on 2020-03-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bosque', '0010_auto_20200218_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fauna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreFauna', models.CharField(max_length=10)),
                ('plantas', models.ManyToManyField(to='bosque.Animal')),
            ],
            options={
                'ordering': ['nombreFauna'],
            },
        ),
    ]
