# Generated by Django 2.2.11 on 2020-03-19 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bosque', '0011_fauna'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fauna',
            old_name='plantas',
            new_name='animales',
        ),
    ]
