# Generated by Django 2.2.10 on 2020-04-06 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0002_cuestionario_pregunta_respuesta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuesta',
            name='preguntaID',
        ),
        migrations.DeleteModel(
            name='Cuestionario',
        ),
        migrations.DeleteModel(
            name='Pregunta',
        ),
        migrations.DeleteModel(
            name='Respuesta',
        ),
    ]
