# Generated by Django 2.2.10 on 2020-04-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0004_cuestionario_pregunta_respuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='textoRespuesta',
            field=models.CharField(choices=[('R1', '1'), ('R2', '2'), ('R3', '3'), ('R4', '4'), ('R5', '5')], max_length=1),
        ),
    ]
