# Generated by Django 2.2.10 on 2020-04-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0005_auto_20200406_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuestionario',
            name='materias',
            field=models.ManyToManyField(to='evaluaciones.Pregunta'),
        ),
    ]
