# Generated by Django 2.2.10 on 2020-04-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0007_auto_20200406_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuestionario',
            name='preguntas',
        ),
        migrations.RemoveField(
            model_name='cuestionario',
            name='titulo',
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='r1',
            field=models.CharField(choices=[('R1', '1'), ('R2', '2'), ('R3', '3'), ('R4', '4'), ('R5', '5')], default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='r10',
            field=models.CharField(choices=[('R1', '1'), ('R2', '2'), ('R3', '3'), ('R4', '4'), ('R5', '5')], default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='r11',
            field=models.CharField(choices=[('R1', '1'), ('R2', '2'), ('R3', '3'), ('R4', '4'), ('R5', '5')], default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='r12',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='r2',
            field=models.CharField(choices=[('R1', '1'), ('R2', '2'), ('R3', '3'), ('R4', '4'), ('R5', '5')], default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='r3',
            field=models.CharField(choices=[('R1', '1'), ('R2', '2'), ('R3', '3'), ('R4', '4'), ('R5', '5')], default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='r4',
            field=models.CharField(choices=[('R1', '1'), ('R2', '2'), ('R3', '3'), ('R4', '4'), ('R5', '5')], default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='r5',
            field=models.CharField(choices=[('R1', '1'), ('R2', '2'), ('R3', '3'), ('R4', '4'), ('R5', '5')], default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='r6',
            field=models.CharField(choices=[('R1', '1'), ('R2', '2'), ('R3', '3'), ('R4', '4'), ('R5', '5')], default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='r7',
            field=models.CharField(choices=[('R1', '1'), ('R2', '2'), ('R3', '3'), ('R4', '4'), ('R5', '5')], default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='r8',
            field=models.CharField(choices=[('R1', '1'), ('R2', '2'), ('R3', '3'), ('R4', '4'), ('R5', '5')], default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='r9',
            field=models.CharField(choices=[('R1', '1'), ('R2', '2'), ('R3', '3'), ('R4', '4'), ('R5', '5')], default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pregunta',
            name='textoRespuesta',
            field=models.CharField(choices=[('R1', '1'), ('R2', '2'), ('R3', '3'), ('R4', '4'), ('R5', '5')], default='', max_length=1),
            preserve_default=False,
        ),
    ]
