# Generated by Django 2.2.10 on 2020-04-06 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0008_auto_20200406_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='textoRespuesta',
        ),
        migrations.DeleteModel(
            name='Respuesta',
        ),
    ]
