# Generated by Django 2.2.10 on 2020-04-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0009_auto_20200406_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='r1',
            field=models.CharField(choices=[('R1', '1'), ('R2', '2'), ('R3', '3'), ('R4', '4'), ('R5', '5')], max_length=2),
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='r10',
            field=models.CharField(choices=[('R1', '1'), ('R2', '2'), ('R3', '3'), ('R4', '4'), ('R5', '5')], max_length=2),
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='r11',
            field=models.CharField(choices=[('R1', '1'), ('R2', '2'), ('R3', '3'), ('R4', '4'), ('R5', '5')], max_length=2),
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='r2',
            field=models.CharField(choices=[('R1', '1'), ('R2', '2'), ('R3', '3'), ('R4', '4'), ('R5', '5')], max_length=2),
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='r3',
            field=models.CharField(choices=[('R1', '1'), ('R2', '2'), ('R3', '3'), ('R4', '4'), ('R5', '5')], max_length=2),
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='r4',
            field=models.CharField(choices=[('R1', '1'), ('R2', '2'), ('R3', '3'), ('R4', '4'), ('R5', '5')], max_length=2),
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='r5',
            field=models.CharField(choices=[('R1', '1'), ('R2', '2'), ('R3', '3'), ('R4', '4'), ('R5', '5')], max_length=2),
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='r6',
            field=models.CharField(choices=[('R1', '1'), ('R2', '2'), ('R3', '3'), ('R4', '4'), ('R5', '5')], max_length=2),
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='r7',
            field=models.CharField(choices=[('R1', '1'), ('R2', '2'), ('R3', '3'), ('R4', '4'), ('R5', '5')], max_length=2),
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='r8',
            field=models.CharField(choices=[('R1', '1'), ('R2', '2'), ('R3', '3'), ('R4', '4'), ('R5', '5')], max_length=2),
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='r9',
            field=models.CharField(choices=[('R1', '1'), ('R2', '2'), ('R3', '3'), ('R4', '4'), ('R5', '5')], max_length=2),
        ),
    ]
