# Generated by Django 2.2.10 on 2020-05-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0010_auto_20200430_1128'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Formulario',
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='r1',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='r10',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='r11',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='r2',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='r3',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='r4',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='r5',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='r6',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='r7',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='r8',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='r9',
            field=models.CharField(max_length=2),
        ),
    ]
