# Generated by Django 2.2.10 on 2020-06-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0013_cuestionario_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuestionario',
            name='r1',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='r10',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='r11',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='r2',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='r3',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='r4',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='r5',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='r6',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='r7',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='r8',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='r9',
            field=models.CharField(max_length=3),
        ),
    ]
