# Generated by Django 2.2.12 on 2020-05-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0040_remove_usuario_nombreusuario'),
        ('inscripcionTesis', '0002_tesis_alumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='tesis',
            name='comiteTutorial',
            field=models.ManyToManyField(to='usuario.Profesor'),
        ),
    ]
