# Generated by Django 2.2.12 on 2020-05-19 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0040_remove_usuario_nombreusuario'),
        ('inscripcionTesis', '0003_tesis_comitetutorial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tesis',
            old_name='comiteTutorial',
            new_name='directores',
        ),
        migrations.CreateModel(
            name='ComiteTutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miembros', models.ManyToManyField(to='usuario.Profesor')),
                ('tesis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inscripcionTesis.Tesis')),
            ],
        ),
    ]
