# Generated by Django 2.2.13 on 2020-06-16 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcionTesis', '0004_auto_20200616_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='tesis',
            name='numeroTesis',
            field=models.IntegerField(default=0),
        ),
    ]
