# Generated by Django 2.2.13 on 2020-06-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcionTesis', '0004_auto_20200519_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tesis',
            name='id',
        ),
        migrations.AddField(
            model_name='tesis',
            name='abstrac',
            field=models.CharField(default='', max_length=5000, verbose_name='Abstrac de la tesis'),
        ),
        migrations.AddField(
            model_name='tesis',
            name='director1',
            field=models.CharField(default='', max_length=50, verbose_name='Ingresar nombre de director 1'),
        ),
        migrations.AddField(
            model_name='tesis',
            name='director2',
            field=models.CharField(default='', max_length=50, verbose_name='Ingresar nombre de director 2'),
        ),
        migrations.AddField(
            model_name='tesis',
            name='idTesis',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tesis',
            name='alumno',
            field=models.CharField(default='', max_length=100, verbose_name='Titulo de la tesis'),
        ),
        migrations.AlterField(
            model_name='tesis',
            name='nombreTesis',
            field=models.CharField(default='', max_length=500, verbose_name='Titulo de la tesis'),
        ),
    ]
