# Generated by Django 2.2.13 on 2020-06-16 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcionTesis', '0005_auto_20200616_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tesis',
            name='directores',
        ),
    ]
