# Generated by Django 2.2.13 on 2020-06-16 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcionTesis', '0007_auto_20200616_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tesis',
            name='director2',
        ),
        migrations.RemoveField(
            model_name='tesis',
            name='director2Aps',
        ),
        migrations.AlterField(
            model_name='tesis',
            name='alumnoAps',
            field=models.CharField(default='', max_length=100, verbose_name='Apeido(s) del alumno autor'),
        ),
        migrations.AlterField(
            model_name='tesis',
            name='director1',
            field=models.CharField(default='', max_length=50, verbose_name='Nombre de director 1'),
        ),
        migrations.AlterField(
            model_name='tesis',
            name='director1Aps',
            field=models.CharField(default='', max_length=50, verbose_name='Apeido(s) de director 1'),
        ),
    ]
