# Generated by Django 2.2.13 on 2020-06-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcionTesis', '0008_auto_20200616_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tesis',
            name='abstrac',
        ),
        migrations.RemoveField(
            model_name='tesis',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='tesis',
            name='alumnoAps',
        ),
        migrations.RemoveField(
            model_name='tesis',
            name='director1',
        ),
        migrations.RemoveField(
            model_name='tesis',
            name='director1Aps',
        ),
        migrations.RemoveField(
            model_name='tesis',
            name='nombreTesis',
        ),
        migrations.RemoveField(
            model_name='tesis',
            name='numeroTesis',
        ),
        migrations.AddField(
            model_name='tesis',
            name='hola',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
