# Generated by Django 2.2.13 on 2020-06-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcionTesis', '0009_auto_20200616_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tesis',
            name='hola',
        ),
        migrations.AddField(
            model_name='tesis',
            name='abstrac',
            field=models.CharField(default='', max_length=5000, verbose_name='Abstrac de la tesis'),
        ),
        migrations.AddField(
            model_name='tesis',
            name='alumno',
            field=models.CharField(default='', max_length=100, verbose_name='Nombre del alumno autor'),
        ),
        migrations.AddField(
            model_name='tesis',
            name='alumnoAps',
            field=models.CharField(default='', max_length=100, verbose_name='Apeido(s) del alumno autor'),
        ),
        migrations.AddField(
            model_name='tesis',
            name='diaCreacion',
            field=models.DateField(default='1920-01-01'),
        ),
        migrations.AddField(
            model_name='tesis',
            name='director1',
            field=models.CharField(default='', max_length=50, verbose_name='Nombre de director 1'),
        ),
        migrations.AddField(
            model_name='tesis',
            name='director1Aps',
            field=models.CharField(default='', max_length=50, verbose_name='Apeido(s) de director 1'),
        ),
        migrations.AddField(
            model_name='tesis',
            name='nombreTesis',
            field=models.CharField(default='', max_length=500, verbose_name='Titulo de la tesis'),
        ),
        migrations.AddField(
            model_name='tesis',
            name='numeroTesis',
            field=models.IntegerField(default=0),
        ),
    ]
