# Generated by Django 2.2.13 on 2020-06-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcionTesis', '0012_tesis_valorw2v'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tesis',
            name='abstrac',
            field=models.TextField(default='', null=True, verbose_name='Abstrac de la tesis'),
        ),
    ]
