# Generated by Django 2.2.13 on 2020-06-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcionTesis', '0014_auto_20200617_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='tesis',
            name='director2',
            field=models.CharField(default='', max_length=50, verbose_name='Nombre de director 1'),
        ),
        migrations.AddField(
            model_name='tesis',
            name='director2Aps',
            field=models.CharField(default='', max_length=50, verbose_name='Apeido(s) de director 1'),
        ),
    ]
