# Generated by Django 2.2.13 on 2020-06-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcionTesis', '0015_auto_20200621_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tesis',
            name='director2',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='Nombre de director 1'),
        ),
        migrations.AlterField(
            model_name='tesis',
            name='director2Aps',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='Apeido(s) de director 1'),
        ),
    ]
