# Generated by Django 2.2.10 on 2020-02-12 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.IntegerField()),
                ('direccion', models.CharField(max_length=200)),
                ('lada', models.CharField(max_length=4)),
                ('telefono', models.CharField(max_length=10)),
                ('curp', models.CharField(max_length=18)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuario.Usuario')),
                ('numRegistro', models.CharField(max_length=20)),
                ('modalidad', models.BooleanField()),
                ('programa', models.CharField(max_length=20)),
                ('beca', models.IntegerField()),
                ('ingles', models.BooleanField()),
                ('cedula', models.CharField(max_length=20)),
                ('calfEXADEP', models.IntegerField()),
                ('calfGRE', models.IntegerField()),
                ('promedio', models.DecimalField(decimal_places=2, max_digits=2)),
                ('escuelaLic', models.CharField(max_length=100)),
                ('lugarLic', models.CharField(max_length=100)),
                ('carrera', models.CharField(max_length=50)),
                ('titulo', models.TextField()),
                ('entrevista', models.CharField(max_length=20)),
            ],
            bases=('usuario.usuario',),
        ),
        migrations.CreateModel(
            name='PersonalAdministravito',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuario.Usuario')),
                ('numEmpleado', models.IntegerField()),
                ('departamento', models.CharField(max_length=50)),
            ],
            bases=('usuario.usuario',),
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuario.Usuario')),
                ('tiraMaterias', models.TextField()),
                ('titulo', models.FileField(upload_to=None)),
                ('cedula', models.CharField(max_length=20)),
                ('numEmpleado', models.IntegerField()),
            ],
            bases=('usuario.usuario',),
        ),
    ]
