# Generated by Django 2.2.10 on 2020-02-18 18:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuario', '0006_auto_20200218_1206'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonalAdministravito',
            new_name='PersonalAdministrativo',
        ),
    ]
