# Generated by Django 2.2.10 on 2020-02-19 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_auto_20200218_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='usuario',
            new_name='nombreUsuario',
        ),
    ]
