# Generated by Django 2.2.10 on 2020-02-22 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0012_auto_20200222_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisos',
            name='charAint',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
