# Generated by Django 2.2.10 on 2020-02-22 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0017_auto_20200222_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='permisos',
            name='numeroBlank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
