# Generated by Django 2.2.10 on 2020-03-12 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0018_permisos_numeroblank'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fechaNacimiento',
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='nacionalidad',
            field=models.CharField(choices=[('AL', 'Alemania'), ('BR', 'Brasil'), ('CA', 'Canada'), ('DI', 'Dinamarca'), ('EC', 'Ecuador')], default='AL', max_length=2),
        ),
    ]
