# Generated by Django 2.2.10 on 2020-03-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0019_auto_20200312_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fechaNacimiento',
            field=models.DateField(auto_now_add=True),
        ),
    ]
