# Generated by Django 2.2.10 on 2020-03-12 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0022_auto_20200312_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='nacionalidad',
            new_name='paisNacimiento',
        ),
    ]
