# Generated by Django 2.2.10 on 2020-03-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0023_auto_20200312_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='numRegistro',
        ),
        migrations.RemoveField(
            model_name='personaladministrativo',
            name='numEmpleado',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='numEmpleado',
        ),
        migrations.AddField(
            model_name='usuario',
            name='identificador',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
