# Generated by Django 2.2.10 on 2020-03-15 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0025_auto_20200315_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='titulo',
        ),
    ]
