# Generated by Django 2.2.10 on 2020-03-15 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0026_auto_20200315_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='beca',
            field=models.CharField(choices=[('1', 'Institucional Estuio'), ('1', 'Institucional Tesis'), ('2', 'Transporte'), ('3', 'BEIFI'), ('4', 'Excelencia')], default='1', max_length=20),
        ),
    ]
