# Generated by Django 2.2.10 on 2020-03-15 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0024_usuario_genero'),
        ('usuario', '0027_auto_20200315_1608'),
    ]

    operations = [
    ]
