# Generated by Django 2.2.11 on 2020-03-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0028_merge_20200315_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='identificador',
        ),
        migrations.AddField(
            model_name='alumno',
            name='numRegistro',
            field=models.CharField(max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumno',
            name='titulo',
            field=models.TextField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personaladministrativo',
            name='numEmpleado',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesor',
            name='numEmpleado',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesor',
            name='titulo',
            field=models.FileField(upload_to=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alumno',
            name='beca',
            field=models.IntegerField(),
        ),
    ]
