# Generated by Django 2.2.10 on 2020-03-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0029_auto_20200317_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='paisNacimiento',
            field=models.CharField(choices=[('ALEMANIA', 'Alemania'), ('BRASIL', 'Brasil'), ('CANADA', 'Canada'), ('DINAMARCA', 'Dinamarca'), ('ECUADOR', 'Ecuador'), ('MEXICO', 'Mexico')], default='MEXICO', max_length=20),
        ),
    ]
