# Generated by Django 2.2.10 on 2020-03-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0030_auto_20200317_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='beca',
            field=models.CharField(choices=[('INSTITUCIONAL_ESTUDIO', 'Institucional Estudio'), ('INSTITUCIONAL_TESIS', 'Institucional Tesis'), ('TRANSPORTE', 'Transporte'), ('BEIFI', 'BEIFI'), ('EXCELENCIA', 'Excelencia')], default='1', max_length=20),
        ),
    ]
