# Generated by Django 2.2.10 on 2020-03-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0031_auto_20200317_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='programa',
            field=models.CharField(max_length=50),
        ),
    ]
