# Generated by Django 2.2.11 on 2020-03-17 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0029_auto_20200316_0036'),
        ('usuario', '0032_auto_20200317_0440'),
    ]

    operations = [
    ]
