# Generated by Django 2.2.11 on 2020-03-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0033_merge_20200317_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='numRegistro',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='personaladministrativo',
            name='numEmpleado',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='numEmpleado',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='titulo',
        ),
        migrations.AddField(
            model_name='usuario',
            name='identificador',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alumno',
            name='beca',
            field=models.CharField(choices=[('INSTITUCIONAL_ESTUDIO', 'Institucional Estudio'), ('INSTITUCIONAL_TESIS', 'Institucional Tesis'), ('TRANSPORTE', 'Transporte'), ('BEIFI', 'BEIFI'), ('EXCELENCIA', 'Excelencia')], default='1', max_length=20),
        ),
    ]
