# Generated by Django 2.2.11 on 2020-03-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0001_initial'),
        ('usuario', '0034_auto_20200317_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='materias',
            field=models.ManyToManyField(to='evaluaciones.Materia'),
        ),
    ]
