# Generated by Django 2.2.11 on 2020-03-19 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0035_profesor_materias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='tiraMaterias',
        ),
    ]
