# Generated by Django 2.2.10 on 2020-03-24 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0039_auto_20200324_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nombreUsuario',
        ),
    ]
